; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=sandbox-vectorizer -sbvec-passes="seed-collection(enable-diff-types)<tr-save,bundle-vec(bottom-up),load-store-vec,tr-accept-or-revert>" -sbvec-collect-seeds=stores,loads -mtriple=amdgpu12-amd-amdhsa %s -S | FileCheck %s

define void @seed_bundle_cross_erasure(ptr addrspace(1) nocapture noalias %a, ptr addrspace(1) nocapture readonly noalias %c) {
; CHECK-LABEL: define void @seed_bundle_cross_erasure(
; CHECK-SAME: ptr addrspace(1) noalias captures(none) [[A:%.*]], ptr addrspace(1) noalias readonly captures(none) [[C:%.*]]) {
; CHECK-NEXT:    [[C_0:%.*]] = getelementptr inbounds i32, ptr addrspace(1) [[C]], i64 0
; CHECK-NEXT:    [[A_0:%.*]] = getelementptr inbounds i32, ptr addrspace(1) [[A]], i64 0
; CHECK-NEXT:    [[VECL:%.*]] = load <2 x i32>, ptr addrspace(1) [[C_0]], align 4, !sandboxvec [[META0:![0-9]+]]
; CHECK-NEXT:    store <2 x i32> [[VECL]], ptr addrspace(1) [[A_0]], align 4, !sandboxvec [[META0]]
; CHECK-NEXT:    ret void
;
  %c.0 = getelementptr inbounds i32, ptr addrspace(1) %c, i64 0
  %a.0 = getelementptr inbounds i32, ptr addrspace(1) %a, i64 0
  %c.1 = getelementptr inbounds i32, ptr addrspace(1) %c, i64 1
  %a.1 = getelementptr inbounds i32, ptr addrspace(1) %a, i64 1
  %ld0 = load i32, ptr addrspace(1) %c.0, align 4
  store i32 %ld0, ptr addrspace(1) %a.0, align 4
  %ld1 = load i32, ptr addrspace(1) %c.1, align 4
  store i32 %ld1, ptr addrspace(1) %a.1, align 4
  ret void
}
;.
; CHECK: [[META0]] = distinct !{!"sandboxregion"}
;.
